using AspireRunner.Core.Abstractions;
using AspireRunner.Core.Extensions;
using AspireRunner.Core.Models;
using AspireRunner.Installer;
using AspireRunner.Tool.ProcessManager;
using AspireRunner.Tool.ProcessManager.Lpc;
using Microsoft.Extensions.Logging;
using Spectre.Console.Rendering;
using System.ComponentModel;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace AspireRunner.Tool.Commands;

public class RunCommand : AsyncCommand<RunCommand.Settings>
{
    public class Settings : CommandSettings
    {
        [CommandArgument(0, "[version]")]
        [Description("The version of the dashboard to run")]
        public string? Version { get; set; }

        [CommandOption("-b|--browser")]
        [Description("Launch the dashboard in the default browser")]
        public bool LaunchBrowser { get; set; }

        [DefaultValue(18888)]
        [CommandOption("-p|--port")]
        [Description("The port the dashboard will be available on")]
        public int DashboardPort { get; init; }

        [CommandOption("-a|--auth")]
        [Description("Use browser token authentication for the dashboard")]
        public bool UseAuth { get; init; }

        [CommandOption("-t|--token")]
        [Description("The token to use for dashboard authentication, if not passed, the token will be randomly generated by the dashboard")]
        public string? AuthToken { get; set; }

        [DefaultValue(true)]
        [CommandOption("-s|--https")]
        [Description("Use HTTPS instead of HTTP, this applies to the dashboard, OTLP and MCP servers")]
        public bool? UseHttps { get; init; }

        [CommandOption("--dashboard-https")]
        [Description("Use HTTPS instead of HTTP for the dashboard, overrides the global HTTPS option")]
        public bool? DashboardHttps { get; init; }

        [DefaultValue(4317)]
        [CommandOption("--otlp-port")]
        [Description("The port the OTLP/gRPC server will listen on, can be disabled by passing 0")]
        public int OtlpPort { get; init; }

        [CommandOption("--otlp-http-port")]
        [Description("The port the OTLP/HTTP server will listen on, by default, only the gRPC server is started")]
        public int? OtlpHttpPort { get; set; }

        [CommandOption("--otlp-key")]
        [Description("The API key to use for the OTLP server")]
        public string? OtlpKey { get; set; }

        [CommandOption("--otlp-https")]
        [Description("Use HTTPS instead of HTTP for the OTLP/gRPC and OTLP/HTTP endpoints, overrides the global HTTPS option")]
        public bool? OtlpHttps { get; set; }

        [CommandOption("--cors-origins")]
        [Description("The allowed origins for CORS requests, separated by a comma. A wildcard (*) can be used to allow any domain")]
        public string? CorsAllowedOrigins { get; set; }

        [CommandOption("--cors-headers")]
        [Description("The allowed headers for CORS requests, separated by a comma")]
        public string? CorsAllowedHeaders { get; set; }

        [DefaultValue("localhost")]
        [CommandOption("--hostname")]
        [Description("The hostname used for the dashboard, OTLP and MCP servers")]
        public string? Hostname { get; set; }

        [DefaultValue(false)]
        [CommandOption("-m|--multiple")]
        [Description("Allow running multiple instances of the dashboard, if not passed, existing instances will be replaced")]
        public bool AllowMultipleInstances { get; set; }

        [DefaultValue(true)]
        [CommandOption("--auto-update")]
        [Description("Automatically update the dashboard to the latest version")]
        public bool? AutoUpdate { get; set; }

        [DefaultValue(18891)]
        [CommandOption("--mcp-port")]
        [Description("The port the MCP server will listen on, can be disabled by passing 0, disabling will remove MCP-related UI in the dashboard")]
        public int McpPort { get; set; }

        [CommandOption("--mcp-key")]
        [Description("The API key to use for the MCP server")]
        public string? McpKey { get; set; }

        [CommandOption("--mcp-https")]
        [Description("Use HTTPS instead of HTTP for the MCP server, overrides the global HTTPS option")]
        public bool? McpHttps { get; set; }

        [CommandOption("--verbose")]
        [Description("Enable verbose logging")]
        public bool? Verbose { get; set; }
    }

    private IDashboard? _dashboard;
    private bool _dashboardStarted;
    private LogRecord[] _currentLog = [];
    private int _currentWidth = AnsiConsole.Profile.Width;
    private int _currentHeight = AnsiConsole.Profile.Height;
    private readonly InMemoryProcessManager _processManager = InMemoryProcessManager.Instance;
    private string _inventoryState = string.Empty;
    private string? _dashboardProcessId;

    protected override async Task<int> ExecuteAsync(CommandContext context, Settings settings, CancellationToken cancellationToken)
    {
        Logger.Verbose = settings.Verbose ?? false;

        if (string.IsNullOrEmpty(DotnetCli.Path))
        {
            Widgets.Write(Widgets.Error("The dotnet CLI was not found, make sure it's installed and available in your PATH environment variable."));
            return -100;
        }

        // Prepare dashboard options
        var dashboardOptions = BuildOptions(settings);
        var otlpEndpoints = GetEnabledEndpoints(dashboardOptions);

        if (dashboardOptions.Runner.AutoUpdate)
        {
            var installer = new DashboardInstaller(Logger.DefaultFactory.CreateLogger<DashboardInstaller>());
            Widgets.Write("Checking for updates ");

            var result = await installer.EnsureLatestAsync(cancellationToken).ShowSpinner();
            Widgets.Write(Widgets.SuccessCheck(), true);

            if (result.Installed != result.Latest)
            {
                Widgets.Write([$"Dashboard updated to version {result.Latest} ".Widget(), Widgets.SuccessCheck()], true);
            }
        }

        using var sessionCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
        var sessionToken = sessionCts.Token;

        // Register runner signal handlers
        using var sigInt = PosixSignalRegistration.Create(PosixSignal.SIGINT, SignalHandler);
        using var sigTerm = PosixSignalRegistration.Create(PosixSignal.SIGTERM, SignalHandler);

        // Create and start the dashboard
        var processFactory = new ProcessFactory(Logger.DefaultFactory.CreateLogger<ProcessFactory>(), Logger.DefaultFactory);
        using var lpcServer = StartLpcServer(processFactory, () =>
        {
            sessionCts.Cancel();
            return Task.CompletedTask;
        });
        if (lpcServer is not null)
        {
            Widgets.WriteInterpolated($"LPC endpoint [{Widgets.PrimaryColorText}]127.0.0.1:{lpcServer.Port}[/] is available for ProcessManager.Client", true);
        }

        _dashboard = await processFactory.CreateAspireDashboardAsync(dashboardOptions);
        if (_dashboard is null)
        {
            Widgets.Write("No dashboards found. Installing the latest version...", true);
            var installationResult = await new InstallCommand().ExecuteFromRunCommandAsync(context, new() { Version = "latest" }, cancellationToken);
            if (installationResult is not 0)
            {
                return installationResult;
            }

            _dashboard = await processFactory.CreateAspireDashboardAsync(dashboardOptions);
            if (_dashboard is null)
            {
                Widgets.Write(Widgets.Error("Failed to create a dashboard instance after installation"));
                return -1;
            }
        }

        if (settings.Version is not null && !VersionRange.Parse(settings.Version, true).IsSatisfied(_dashboard.Version))
        {
            Widgets.Write(Widgets.Error($"No version matching '{settings.Version}' is installed, run '{RunnerInfo.CommandName} aspire install {settings.Version}' to install it"));
            return 2;
        }

        Widgets.WriteInterpolated($"Found dashboard version [{Widgets.PrimaryColorText}]{_dashboard.Version}[/] at {_dashboard.InstallationPath}", true);

        await _dashboard.StartAsync(sessionToken);
        _dashboardStarted = _dashboard.IsRunning;

        if (!_dashboardStarted)
        {
            var (dashboard, runner) = Dashboard.TryGetRunningInstance();
            if (dashboard.IsRunning() || runner.IsRunning())
            {
                Widgets.Write(Widgets.Error($"Another instance of the dashboard is already running{Environment.NewLine}Runner PID: [{Widgets.PrimaryColorText}]{runner?.Id}[/], Dashboard PID: [{Widgets.PrimaryColorText}]{dashboard?.Id}[/]"));
                return -2;
            }

            Widgets.Write(Widgets.Error("Failed to start the dashboard"));
            return -1;
        }

        SyncDashboardInventory();

        // Prepare a single interactive workspace with clearly separated boundaries:
        // left side = managed processes + selected process logs, right side = Aspire status + Aspire logs.
        var defaultStatus = Widgets.StatusSymbol(false);
        var table = new Table()
            .Collapse()
            .BorderStyle(new Style(Widgets.PrimaryColor, decoration: Decoration.Dim))
            .AddColumn("", c => c.Centered().Width(14).NoWrap())
            .AddColumn("Status", c => c.Centered().Width(12))
            .AddColumn("Port", c => c.Centered().Width(10))
            .AddColumn("Authentication", c => c.Centered().Width(30).NoWrap())
            .AddRow("Dashboard".Widget(), defaultStatus)
            .AddRow("OTLP/gRPC".Widget(), defaultStatus)
            .AddRow("OTLP/HTTP".Widget(), defaultStatus)
            .AddRow("MCP".Widget(), defaultStatus);

        var actions = new Columns(
            Widgets.KeyActionDescriptor("↑/↓", "Select process"),
            Widgets.KeyActionDescriptor("L", "Reload logs"),
            Widgets.KeyActionDescriptor("S", "Stop selected"),
            Widgets.KeyActionDescriptor("R", "Restart selected"),
            Widgets.KeyActionDescriptor("D", "Delete selected"),
            Widgets.KeyActionDescriptor("K", "Kill all + exit"),
            Widgets.KeyActionDescriptor("B", "Open browser"),
            Widgets.KeyActionDescriptor("H", "Help"),
            Widgets.KeyActionDescriptor("Esc/Ctrl+C", "Exit")
        ).Collapse().PadRight(3);

        var actionStatus = "Select a process, then use S/R/D actions. Logs panel includes history + live updates.";
        var selectedProcessId = string.Empty;
        var processLogEntries = new List<(string Stream, string Message)>();
        var processLogCursors = new Dictionary<string, (int StdoutCount, int StderrCount)>(StringComparer.OrdinalIgnoreCase);
        var processLogsProcessId = string.Empty;
        var reloadSelectedProcessLogs = true;
        var serviceStatusState = string.Empty;
        var selectedDetailsState = string.Empty;
        var killRequested = false;
        const int maxProcessLogLines = 300;

        var mainLayout = new Layout("main").SplitRows(
            new Layout("header", BuildHeader()).Ratio(1),
            new Layout("body").SplitColumns(
                new Layout("left").SplitRows(
                    new Layout("processes", BuildProcessPanel()).Ratio(7),
                    new Layout("process-logs", BuildProcessLogsPanel()).Ratio(8)
                ).Ratio(3),
                new Layout("right").SplitRows(
                    new Layout("aspire-status", BuildAspireStatusPanel()).Ratio(5),
                    new Layout("process-details", BuildProcessDetailsPanel()).Ratio(8)
                ).Ratio(2)
            ).Ratio(14),
            new Layout("footer", BuildFooterPanel()).Ratio(2)
        );

        EnsureSelectedProcess();
        UpdateAspireStatusPanel();
        UpdateProcessPanel();
        UpdateProcessDetailsPanel();
        UpdateProcessLogsPanel(forceReload: true);
        UpdateFooterPanel();
        serviceStatusState = BuildServiceStatusState();
        selectedDetailsState = BuildSelectedProcessDetailsState();

        ConsoleCancelEventHandler cancelHandler = (_, e) =>
        {
            e.Cancel = true;
            sessionCts.Cancel();
        };

        Console.CancelKeyPress += cancelHandler;

        try
        {
            // Render the live layout (with spinners) while the dashboard is still initializing
            await RenderLiveInitializationAsync();

            await AnsiConsole.Live(mainLayout)
                .Overflow(VerticalOverflow.Crop)
                .Cropping(VerticalOverflowCropping.Bottom)
                .AutoClear(false)
                .StartAsync(async ctx =>
                {
                    ctx.Refresh();

                    while (!sessionToken.IsCancellationRequested)
                    {
                        var shouldRefresh = CheckDashboardStatusChanged()
                            | CheckServiceStatusChanged()
                            | CheckConsoleSizeChanged()
                            | CheckInventoryChanged()
                            | CheckSelectedProcessLogEntries()
                            | CheckSelectedProcessDetailsChanged();

                        if (Console.KeyAvailable)
                        {
                            var pressedKey = Console.ReadKey(true);
                            var keyHandled = true;
                            switch (pressedKey.Key)
                            {
                                case ConsoleKey.UpArrow:
                                {
                                    MoveSelection(-1);
                                    break;
                                }
                                case ConsoleKey.DownArrow:
                                {
                                    MoveSelection(1);
                                    break;
                                }
                                case ConsoleKey.L:
                                {
                                    reloadSelectedProcessLogs = true;
                                    actionStatus = "Reloading selected process logs (history + live)...";
                                    UpdateFooterPanel();
                                    break;
                                }
                                case ConsoleKey.S:
                                {
                                    await StopSelectedProcessAsync();
                                    break;
                                }
                                case ConsoleKey.R:
                                {
                                    await RestartSelectedProcessAsync();
                                    break;
                                }
                                case ConsoleKey.D:
                                {
                                    await DeleteSelectedProcessAsync();
                                    break;
                                }
                                case ConsoleKey.K:
                                {
                                    killRequested = true;
                                    actionStatus = "Killing runner and all managed processes...";
                                    UpdateFooterPanel();
                                    sessionCts.Cancel();
                                    break;
                                }
                                case ConsoleKey.H or ConsoleKey.Help:
                                {
                                    if (PlatformHelper.GetUrlOpener(RunnerInfo.ProjectUrl) is { } opener)
                                    {
                                        ProcessHelper.Run(opener.Executable, opener.Arguments);
                                        actionStatus = "Opened project documentation/help.";
                                        UpdateFooterPanel();
                                    }

                                    break;
                                }
                                case ConsoleKey.B:
                                {
                                    if (_dashboard is { IsRunning: true, Url: { } url } && PlatformHelper.GetUrlOpener(url) is { } opener)
                                    {
                                        ProcessHelper.Run(opener.Executable, opener.Arguments);
                                        actionStatus = "Opened Aspire dashboard in browser.";
                                        UpdateFooterPanel();
                                    }

                                    break;
                                }
                                case ConsoleKey.C when pressedKey.Modifiers.HasFlag(ConsoleModifiers.Control):
                                case ConsoleKey.Escape:
                                {
                                    sessionCts.Cancel();
                                    break;
                                }
                                default:
                                {
                                    keyHandled = false;
                                    break;
                                }
                            }

                            shouldRefresh |= keyHandled;
                        }

                        if (shouldRefresh)
                        {
                            ctx.Refresh();
                        }

                        try
                        {
                            await Task.Delay(40, sessionToken).ConfigureAwait(false);
                        }
                        catch (OperationCanceledException)
                        {
                            break;
                        }
                    }
                }).ConfigureAwait(false);

            if (killRequested)
            {
                await KillAllManagedProcessesAsync();
                return 0;
            }

            await ShutdownManagedProcessesAsync();
            return 0;
        }
        finally
        {
            Console.CancelKeyPress -= cancelHandler;
        }

        async Task RenderLiveInitializationAsync()
        {
            var waitingPrompt = new Align(new Text("Waiting for dashboard startup"), HorizontalAlignment.Left, VerticalAlignment.Bottom);
            mainLayout["footer"].Update(new Panel(waitingPrompt)
                .Header($"[{Widgets.PrimaryColorText}]Startup[/]")
                .BorderStyle(new Style(Widgets.PrimaryColor, decoration: Decoration.Dim))
                .Expand());
            AnsiConsole.Clear();

            try
            {
                await AnsiConsole.Live(mainLayout)
                    .Overflow(VerticalOverflow.Crop)
                    .Cropping(VerticalOverflowCropping.Bottom)
                    .StartAsync(async ctx =>
                    {
                        var spinner = !AnsiConsole.Console.Profile.Capabilities.Unicode ? Spinner.Known.Ascii : Spinner.Known.Dots;
                        var frameIndex = 0;

                        while (_dashboard.IsRunning && !sessionToken.IsCancellationRequested)
                        {
                            var currentFrame = new Markup(spinner.Frames[frameIndex % spinner.Frames.Count], Widgets.PrimaryColor);
                            var currentPrompt = new Align(
                                new Columns(currentFrame, new Text("Waiting for dashboard startup")).Collapse(),
                                HorizontalAlignment.Left,
                                VerticalAlignment.Bottom
                            );

                            mainLayout["footer"].Update(new Panel(currentPrompt)
                                .Header($"[{Widgets.PrimaryColorText}]Startup[/]")
                                .BorderStyle(new Style(Widgets.PrimaryColor, decoration: Decoration.Dim))
                                .Expand());

                            UpdateTableCells(currentFrame);
                            UpdateAspireStatusPanel();
                            UpdateProcessPanel();
                            UpdateProcessDetailsPanel();
                            UpdateProcessLogsPanel(forceReload: true);
                            ctx.Refresh();

                            var grpcReady = !otlpEndpoints.Contains("grpc")
                                || (_dashboard.OtlpEndpoints?.Any(endpoint => endpoint.Protocol.Contains("grpc", StringComparison.OrdinalIgnoreCase)) is true);
                            var httpReady = !otlpEndpoints.Contains("http")
                                || (_dashboard.OtlpEndpoints?.Any(endpoint => endpoint.Protocol.Contains("http", StringComparison.OrdinalIgnoreCase)) is true);
                            var otlpReady = grpcReady && httpReady;
                            var mcpReady = dashboardOptions.Mcp.Disabled is true || _dashboard.McpEndpoint != null;

                            if (_dashboard.Url is not null && otlpReady && mcpReady)
                            {
                                break;
                            }

                            frameIndex++;

                            try
                            {
                                await Task.Delay(spinner.Interval, sessionToken).ConfigureAwait(false);
                            }
                            catch (OperationCanceledException)
                            {
                                break;
                            }
                        }
                    }).ConfigureAwait(false);
            }
            catch (OperationCanceledException)
            {
                // Startup can be canceled through Ctrl+C/Esc; treat as normal flow.
            }

            UpdateTableCells(defaultStatus);
            UpdateAspireStatusPanel();
            UpdateProcessPanel();
            UpdateProcessDetailsPanel();
            UpdateProcessLogsPanel(forceReload: true);
            actionStatus = "Runner ready. Select process and use S/R/D/L actions.";
            UpdateFooterPanel();
            serviceStatusState = BuildServiceStatusState();
            selectedDetailsState = BuildSelectedProcessDetailsState();
        }

        void UpdateTableCells(Renderable defaultContent)
        {
            if (_dashboard is null)
            {
                ResetTableCells();
                return;
            }

            var dashboardRunning = _dashboard.IsRunning;

            if (!dashboardRunning || _dashboard.Url is null)
            {
                table.UpdateCell(0, 1, defaultContent);
                table.UpdateCell(0, 2, "");
                table.UpdateCell(0, 3, "");
            }
            else
            {
                table.UpdateCell(0, 1, Widgets.TableColumn([Widgets.StatusSymbol(true)], HorizontalAlignment.Center));
                table.UpdateCell(0, 2, Widgets.TableColumn([$"[{Widgets.PrimaryColorText} link={_dashboard.Url}]{settings.DashboardPort}[/]".Widget()], HorizontalAlignment.Center));
                if (settings.UseAuth)
                {
                    var token = UrlHelper.GetQuery(_dashboard.Url)["t"].Truncate(35);
                    table.UpdateCell(0, 3, Widgets.TableColumn([$"[{Widgets.PrimaryColorText}]{token}[/]".Widget()], HorizontalAlignment.Center));
                }
            }

            if (!dashboardRunning
                || !otlpEndpoints.Contains("grpc")
                || _dashboard.OtlpEndpoints?.FirstOrDefault(e => e.Protocol.Contains("grpc", StringComparison.OrdinalIgnoreCase)) is null)
            {
                table.UpdateCell(1, 1, defaultContent);
                table.UpdateCell(1, 2, "");
                table.UpdateCell(1, 3, "");
            }
            else
            {
                table.UpdateCell(1, 1, Widgets.TableColumn([Widgets.StatusSymbol(true)], HorizontalAlignment.Center));
                table.UpdateCell(1, 2, Widgets.TableColumn([$"[{Widgets.PrimaryColorText}]{settings.OtlpPort}[/]".Widget()], HorizontalAlignment.Center));
                if (!string.IsNullOrWhiteSpace(settings.OtlpKey))
                {
                    table.UpdateCell(1, 3, Widgets.TableColumn([$"x-otlp-api-key=[{Widgets.PrimaryColorText}]{settings.OtlpKey.Truncate(18)}[/]".Widget()], HorizontalAlignment.Center));
                }
            }

            if (!dashboardRunning
                || !otlpEndpoints.Contains("http")
                || _dashboard.OtlpEndpoints?.FirstOrDefault(e => e.Protocol.Contains("http", StringComparison.OrdinalIgnoreCase)) is null)
            {
                table.UpdateCell(2, 1, defaultContent);
                table.UpdateCell(2, 2, "");
                table.UpdateCell(2, 3, "");
            }
            else
            {
                table.UpdateCell(2, 1, Widgets.TableColumn([Widgets.StatusSymbol(true)], HorizontalAlignment.Center));
                table.UpdateCell(2, 2, Widgets.TableColumn([$"[{Widgets.PrimaryColorText}]{settings.OtlpHttpPort}[/]".Widget()], HorizontalAlignment.Center));
                if (!string.IsNullOrWhiteSpace(settings.OtlpKey))
                {
                    table.UpdateCell(2, 3, Widgets.TableColumn([$"x-otlp-api-key=[{Widgets.PrimaryColorText}]{settings.OtlpKey.Truncate(18)}[/]".Widget()], HorizontalAlignment.Center));
                }
            }

            if (!dashboardRunning || dashboardOptions.Mcp.Disabled is true || _dashboard.McpEndpoint is null)
            {
                table.UpdateCell(3, 1, defaultContent);
                table.UpdateCell(3, 2, "");
                table.UpdateCell(3, 3, "");
            }
            else
            {
                table.UpdateCell(3, 1, Widgets.TableColumn([Widgets.StatusSymbol(true)], HorizontalAlignment.Center));
                table.UpdateCell(3, 2, Widgets.TableColumn([$"[{Widgets.PrimaryColorText}]{settings.McpPort}[/]".Widget()], HorizontalAlignment.Center));
                if (!string.IsNullOrWhiteSpace(settings.McpKey))
                {
                    table.UpdateCell(3, 3, Widgets.TableColumn([$"x-mcp-api-key=[{Widgets.PrimaryColorText}]{settings.McpKey.Truncate(18)}[/]".Widget()], HorizontalAlignment.Center));
                }
            }
        }

        void ResetTableCells()
        {
            table.UpdateCell(0, 1, defaultStatus);
            table.UpdateCell(0, 2, "");
            table.UpdateCell(0, 3, "");
            table.UpdateCell(1, 1, defaultStatus);
            table.UpdateCell(1, 2, "");
            table.UpdateCell(1, 3, "");
            table.UpdateCell(2, 1, defaultStatus);
            table.UpdateCell(2, 2, "");
            table.UpdateCell(2, 3, "");
            table.UpdateCell(3, 1, defaultStatus);
            table.UpdateCell(3, 2, "");
            table.UpdateCell(3, 3, "");
        }

        bool CheckDashboardStatusChanged()
        {
            var dashboardRunning = _dashboard.IsRunning;
            if (dashboardRunning == _dashboardStarted)
            {
                // status is unchanged
                return false;
            }

            if (dashboardRunning)
            {
                _dashboardStarted = true;
                UpdateTableCells(defaultStatus);
            }
            else
            {
                _dashboardStarted = false;
                ResetTableCells();
            }

            SyncDashboardInventory();

            return true;
        }

        bool CheckConsoleSizeChanged()
        {
            if (AnsiConsole.Profile.Width == _currentWidth && AnsiConsole.Profile.Height == _currentHeight)
            {
                return false;
            }

            _currentWidth = AnsiConsole.Profile.Width;
            _currentHeight = AnsiConsole.Profile.Height;

            mainLayout["header"].Update(BuildHeader()).Ratio(1);
            UpdateTableCells(defaultStatus);
            UpdateAspireStatusPanel();
            UpdateProcessPanel();
            UpdateProcessDetailsPanel();
            UpdateProcessLogsPanel(forceReload: true);
            UpdateFooterPanel();
            serviceStatusState = BuildServiceStatusState();
            selectedDetailsState = BuildSelectedProcessDetailsState();

            return true;
        }

        bool CheckInventoryChanged()
        {
            SyncDashboardInventory();

            var snapshot = BuildInventoryState();
            if (snapshot == _inventoryState)
            {
                return false;
            }

            EnsureSelectedProcess();
            UpdateProcessPanel();
            UpdateProcessDetailsPanel();
            reloadSelectedProcessLogs = true;
            return true;
        }

        bool CheckServiceStatusChanged()
        {
            var snapshot = BuildServiceStatusState();
            if (snapshot == serviceStatusState)
            {
                return false;
            }

            serviceStatusState = snapshot;
            UpdateTableCells(defaultStatus);
            UpdateAspireStatusPanel();
            SyncDashboardInventory();
            return true;
        }

        void SyncDashboardInventory()
        {
            if (_dashboard is null)
            {
                return;
            }

            var dashboardExe = DotnetCli.Executable;
            var dashboardArgs = $"exec {Path.Combine(_dashboard.InstallationPath, Dashboard.DllName)}";
            var dashboardEnvironment = dashboardOptions.ToEnvironmentVariables();
            var command = $"{RunnerInfo.CommandName} aspire run {settings.Version}".TrimEnd();
            var details = BuildDashboardDetails();
            var dashboardPorts = GetDashboardPorts();

            if (string.IsNullOrWhiteSpace(_dashboardProcessId))
            {
                var processEntry = _processManager.Register(
                    _dashboard,
                    ProcessProfile.AspireDashboard,
                    command,
                    details,
                    preferredId: "aspire-dashboard",
                    executable: dashboardExe,
                    arguments: dashboardArgs,
                    environmentVariables: BuildEnvironmentString(dashboardEnvironment),
                    workingDirectory: _dashboard.InstallationPath,
                    exposedPorts: dashboardPorts);
                _dashboardProcessId = processEntry.Id;
                return;
            }

            _processManager.UpdateMetadata(
                _dashboardProcessId,
                command,
                details,
                executable: dashboardExe,
                arguments: dashboardArgs,
                environmentVariables: BuildEnvironmentString(dashboardEnvironment),
                workingDirectory: _dashboard.InstallationPath,
                exposedPorts: dashboardPorts);
        }

        Table BuildInventoryTable()
        {
            var inventory = new Table()
                .Collapse()
                .BorderStyle(new Style(Widgets.PrimaryColor, decoration: Decoration.Dim))
                .AddColumn("", c => c.Centered().NoWrap().Width(3))
                .AddColumn("Id", c => c.NoWrap().Width(16))
                .AddColumn("Process", c => c.NoWrap().Width(24))
                .AddColumn("Status", c => c.Centered().NoWrap().Width(8))
                .AddColumn("PID", c => c.Centered().NoWrap().Width(8))
                .AddColumn("Ports", c => c.Centered().NoWrap().Width(18))
                .AddColumn("Profile", c => c.Centered().NoWrap().Width(12));

            var entries = _processManager.List();
            if (entries.Count == 0)
            {
                inventory.AddRow(
                    "".Widget(),
                    "-".Widget(),
                    "No managed processes".Widget(),
                    "".Widget(),
                    "".Widget(),
                    "".Widget(),
                    "".Widget());
                return inventory;
            }

            foreach (var entry in entries)
            {
                var running = entry.Process.IsRunning;
                var profileText = entry.Profile switch
                {
                    ProcessProfile.AspireDashboard => "Aspire",
                    ProcessProfile.ExecutableProcess => "Executable",
                    _ => entry.Profile.ToString()
                };

                var selected = selectedProcessId.Equals(entry.Id, StringComparison.OrdinalIgnoreCase);
                var selector = selected ? $"[{Widgets.PrimaryColorText}]>[/]" : " ";

                inventory.AddRow(
                    selector.Widget(),
                    entry.Id.Truncate(16).Widget(),
                    entry.Process.DisplayName.Truncate(24).Widget(),
                    Widgets.TableColumn([Widgets.StatusSymbol(running)], HorizontalAlignment.Center),
                    (entry.Process.Pid?.ToString() ?? string.Empty).Widget(),
                    BuildPortLinks(entry.ExposedPorts),
                    profileText.Widget());
            }

            return inventory;
        }

        IRenderable BuildPortLinks(IReadOnlyList<int> ports)
        {
            if (ports.Count == 0)
            {
                return "-".Widget();
            }

            var links = string.Join("[grey],[/]", ports
                .Where(port => port is > ushort.MinValue and <= ushort.MaxValue)
                .OrderBy(port => port)
                .Select(port => $"[{Widgets.PrimaryColorText}][link=http://127.0.0.1:{port}]{port}[/][/]"));

            return new Markup(links);
        }

        IRenderable BuildHeader()
        {
            var rows = new Rows(
                new Markup($"[{Widgets.PrimaryColorText} bold]Aspire Runner[/]"),
                new Markup($"[{Widgets.PrimaryColorText} dim]v{RunnerInfo.Version}[/]"))
                .Collapse();

            return new Align(rows, HorizontalAlignment.Center, VerticalAlignment.Middle);
        }

        void UpdateAspireStatusPanel()
        {
            mainLayout["aspire-status"].Update(BuildAspireStatusPanel());
        }

        void UpdateProcessDetailsPanel()
        {
            mainLayout["process-details"].Update(BuildProcessDetailsPanel());
            selectedDetailsState = BuildSelectedProcessDetailsState();
        }

        bool CheckSelectedProcessDetailsChanged()
        {
            var snapshot = BuildSelectedProcessDetailsState();
            if (snapshot == selectedDetailsState)
            {
                return false;
            }

            UpdateProcessDetailsPanel();
            return true;
        }

        string BuildServiceStatusState()
        {
            if (_dashboard is null)
            {
                return string.Empty;
            }

            var endpointState = string.Join(';', (_dashboard.OtlpEndpoints ?? [])
                .Select(endpoint => $"{endpoint.Protocol}:{endpoint.Url}")
                .OrderBy(item => item, StringComparer.OrdinalIgnoreCase));

            return $"{_dashboard.IsRunning}|{_dashboard.Url}|{_dashboard.McpEndpoint}|{endpointState}";
        }

        string BuildSelectedProcessDetailsState()
        {
            var selected = GetSelectedProcessEntry();
            if (selected is null)
            {
                return string.Empty;
            }

            return string.Join('|',
                selected.Id,
                selected.Process.IsRunning,
                selected.Process.Pid,
                selected.Profile,
                selected.Command,
                selected.Details,
                selected.WorkingDirectory,
                string.Join(',', selected.ExposedPorts),
                selected.LastUpdatedAt.ToUnixTimeMilliseconds());
        }

        void UpdateProcessPanel()
        {
            mainLayout["processes"].Update(BuildProcessPanel());
            _inventoryState = BuildInventoryState();
        }

        void UpdateProcessLogsPanel(bool forceReload = false)
        {
            var changed = UpdateSelectedProcessLogs(forceReload);
            if (changed || forceReload)
            {
                mainLayout["process-logs"].Update(BuildProcessLogsPanel());
            }
        }

        bool CheckSelectedProcessLogEntries()
        {
            var changed = UpdateSelectedProcessLogs(reloadSelectedProcessLogs);
            reloadSelectedProcessLogs = false;
            if (changed)
            {
                mainLayout["process-logs"].Update(BuildProcessLogsPanel());
            }

            return changed;
        }

        bool UpdateSelectedProcessLogs(bool forceReload)
        {
            EnsureSelectedProcess();
            var selected = GetSelectedProcessEntry();

            if (selected is null)
            {
                if (processLogEntries.Count == 0 && string.IsNullOrWhiteSpace(processLogsProcessId))
                {
                    return false;
                }

                processLogsProcessId = string.Empty;
                processLogEntries.Clear();
                return true;
            }

            var changed = false;

            if (forceReload || !processLogsProcessId.Equals(selected.Id, StringComparison.OrdinalIgnoreCase))
            {
                processLogsProcessId = selected.Id;
                processLogEntries.Clear();
                processLogCursors[selected.Id] = (0, 0);
                changed = true;
            }

            if (selected.Process is not IProcessOutputSource outputSource)
            {
                var unsupportedMessage = "Selected process does not expose output streams.";
                if (processLogEntries.Count != 1 || !processLogEntries[0].Message.Equals(unsupportedMessage, StringComparison.Ordinal))
                {
                    processLogEntries.Clear();
                    processLogEntries.Add(("info", unsupportedMessage));
                    return true;
                }

                return changed;
            }

            if (!processLogCursors.TryGetValue(selected.Id, out var cursor))
            {
                cursor = (0, 0);
            }

            var stdoutSnapshot = outputSource.GetStdoutSnapshot();
            var stderrSnapshot = outputSource.GetStderrSnapshot();

            if (stdoutSnapshot.Count < cursor.StdoutCount || stderrSnapshot.Count < cursor.StderrCount)
            {
                processLogEntries.Clear();
                cursor = (0, 0);
                changed = true;
            }

            for (var i = cursor.StdoutCount; i < stdoutSnapshot.Count; i++)
            {
                AppendProcessLog("stdout", stdoutSnapshot[i]);
                changed = true;
            }

            for (var i = cursor.StderrCount; i < stderrSnapshot.Count; i++)
            {
                AppendProcessLog("stderr", stderrSnapshot[i]);
                changed = true;
            }

            processLogCursors[selected.Id] = (stdoutSnapshot.Count, stderrSnapshot.Count);
            return changed;
        }

        void AppendProcessLog(string stream, string line)
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                return;
            }

            processLogEntries.Add((stream, line));
            if (processLogEntries.Count > maxProcessLogLines)
            {
                processLogEntries.RemoveRange(0, processLogEntries.Count - maxProcessLogLines);
            }
        }

        static string ResolveProcessLogColor(string stream, string message)
        {
            var text = message.TrimStart();

            if (text.StartsWith("warn", StringComparison.OrdinalIgnoreCase)
                || text.StartsWith("warning", StringComparison.OrdinalIgnoreCase))
            {
                return "yellow";
            }

            if (text.StartsWith("error", StringComparison.OrdinalIgnoreCase)
                || text.StartsWith("err", StringComparison.OrdinalIgnoreCase)
                || text.StartsWith("fail", StringComparison.OrdinalIgnoreCase)
                || text.StartsWith("fatal", StringComparison.OrdinalIgnoreCase)
                || text.StartsWith("crit", StringComparison.OrdinalIgnoreCase))
            {
                return "red";
            }

            if (text.StartsWith("info", StringComparison.OrdinalIgnoreCase)
                || text.StartsWith("information", StringComparison.OrdinalIgnoreCase)
                || text.StartsWith("debug", StringComparison.OrdinalIgnoreCase)
                || text.StartsWith("trace", StringComparison.OrdinalIgnoreCase))
            {
                return "white";
            }

            return stream.Equals("stderr", StringComparison.OrdinalIgnoreCase) ? "red" : "white";
        }

        IRenderable BuildProcessPanel()
        {
            return new Panel(new Align(BuildInventoryTable(), HorizontalAlignment.Left, VerticalAlignment.Top))
                .Header($"[{Widgets.PrimaryColorText}]Managed Processes[/]")
                .BorderStyle(new Style(Widgets.PrimaryColor, decoration: Decoration.Dim))
                .Expand();
        }

        IRenderable BuildProcessLogsPanel()
        {
            EnsureSelectedProcess();
            var selected = GetSelectedProcessEntry();
            var title = selected is null
                ? "Selected Process Logs"
                : $"Selected Process Logs ({selected.Process.DisplayName})";

            var visibleLines = Math.Max(AnsiConsole.Profile.Height / 5, 6);
            var rows = processLogEntries
                .TakeLast(visibleLines)
                .Select(entry =>
                {
                    var style = ResolveProcessLogColor(entry.Stream, entry.Message);

                    return (IRenderable)new Markup($"[{style}]{Markup.Escape(entry.Message)}[/]");
                })
                .ToArray();

            if (rows.Length == 0)
            {
                rows = [new Text("No logs yet. Use L to reload history for the selected process.", new Style(Color.Grey))];
            }

            return new Panel(new Rows(rows))
                .Header($"[{Widgets.PrimaryColorText}]{Markup.Escape(title)}[/]")
                .BorderStyle(new Style(Widgets.PrimaryColor, decoration: Decoration.Dim))
                .Expand();
        }

        IRenderable BuildAspireStatusPanel()
        {
            return new Panel(new Align(table, HorizontalAlignment.Left, VerticalAlignment.Top))
                .Header($"[{Widgets.PrimaryColorText}]Aspire Services[/]")
                .BorderStyle(new Style(Widgets.PrimaryColor, decoration: Decoration.Dim))
                .Expand();
        }

        IRenderable BuildProcessDetailsPanel()
        {
            var selected = GetSelectedProcessEntry();
            if (selected is null)
            {
                return new Panel(new Text("Select a process to inspect metadata and runtime details.", new Style(Color.Grey)))
                    .Header($"[{Widgets.PrimaryColorText}]Process Details[/]")
                    .BorderStyle(new Style(Widgets.PrimaryColor, decoration: Decoration.Dim))
                    .Expand();
            }

            var profileText = selected.Profile switch
            {
                ProcessProfile.AspireDashboard => "Aspire",
                ProcessProfile.ExecutableProcess => "Executable",
                _ => selected.Profile.ToString()
            };

            var fields = new Grid()
                .AddColumn(new GridColumn().NoWrap())
                .AddColumn();

            fields.AddRow("[grey]Name[/]".Widget(), selected.Process.DisplayName.Truncate(46).Widget());
            fields.AddRow("[grey]Id[/]".Widget(), selected.Id.Truncate(46).Widget());
            fields.AddRow("[grey]Status[/]".Widget(), new Markup(selected.Process.IsRunning ? "[green]Running[/]" : "[red]Stopped[/]"));
            fields.AddRow("[grey]PID[/]".Widget(), (selected.Process.Pid?.ToString() ?? "-").Widget());
            fields.AddRow("[grey]Profile[/]".Widget(), profileText.Widget());
            fields.AddRow("[grey]Ports[/]".Widget(), BuildPortLinks(selected.ExposedPorts));

            if (!string.IsNullOrWhiteSpace(selected.WorkingDirectory))
            {
                fields.AddRow("[grey]Work Dir[/]".Widget(), selected.WorkingDirectory.Truncate(46).Widget());
            }

            if (!string.IsNullOrWhiteSpace(selected.Command))
            {
                fields.AddRow("[grey]Command[/]".Widget(), selected.Command.Truncate(46).Widget());
            }

            if (!string.IsNullOrWhiteSpace(selected.Details))
            {
                fields.AddRow("[grey]Details[/]".Widget(), selected.Details.Truncate(46).Widget());
            }

            fields.AddRow("[grey]Updated[/]".Widget(), selected.LastUpdatedAt.LocalDateTime.ToString("HH:mm:ss").Widget());

            return new Panel(fields)
                .Header($"[{Widgets.PrimaryColorText}]Process Details[/]")
                .BorderStyle(new Style(Widgets.PrimaryColor, decoration: Decoration.Dim))
                .Expand();
        }

        IRenderable BuildFooterPanel()
        {
            var statusText = new Markup($"[{Widgets.PrimaryColorText}]{Markup.Escape(actionStatus)}[/]");
            return new Panel(new Rows(actions, statusText))
                .Header($"[{Widgets.PrimaryColorText}]Controls[/]")
                .BorderStyle(new Style(Widgets.PrimaryColor, decoration: Decoration.Dim))
                .Expand();
        }

        void UpdateFooterPanel()
        {
            mainLayout["footer"].Update(BuildFooterPanel());
        }

        void EnsureSelectedProcess()
        {
            var entries = _processManager.List();
            if (entries.Count == 0)
            {
                selectedProcessId = string.Empty;
                return;
            }

            if (!string.IsNullOrWhiteSpace(selectedProcessId)
                && entries.Any(entry => entry.Id.Equals(selectedProcessId, StringComparison.OrdinalIgnoreCase)))
            {
                return;
            }

            selectedProcessId = entries[0].Id;
        }

        ManagedProcessEntry? GetSelectedProcessEntry()
        {
            if (string.IsNullOrWhiteSpace(selectedProcessId))
            {
                return null;
            }

            return _processManager.List().FirstOrDefault(entry => entry.Id.Equals(selectedProcessId, StringComparison.OrdinalIgnoreCase));
        }

        void MoveSelection(int delta)
        {
            var entries = _processManager.List();
            if (entries.Count == 0)
            {
                selectedProcessId = string.Empty;
                actionStatus = "No managed process available.";
                UpdateFooterPanel();
                return;
            }

            var currentIndex = entries
                .Select((entry, index) => new { entry, index })
                .FirstOrDefault(item => item.entry.Id.Equals(selectedProcessId, StringComparison.OrdinalIgnoreCase))
                ?.index ?? 0;

            var nextIndex = (currentIndex + delta + entries.Count) % entries.Count;
            selectedProcessId = entries[nextIndex].Id;
            reloadSelectedProcessLogs = true;
            actionStatus = $"Selected process: {entries[nextIndex].Process.DisplayName}";

            UpdateProcessPanel();
            UpdateProcessDetailsPanel();
            UpdateProcessLogsPanel(forceReload: true);
            UpdateFooterPanel();
        }

        async Task StopSelectedProcessAsync()
        {
            var selected = GetSelectedProcessEntry();
            if (selected is null)
            {
                actionStatus = "No process selected.";
                UpdateFooterPanel();
                return;
            }

            var selectedDashboard = selected.Id.Equals(_dashboardProcessId, StringComparison.OrdinalIgnoreCase);
            var stopped = await _processManager.StopAsync(selected.Id, CancellationToken.None).ConfigureAwait(false);
            actionStatus = stopped
                ? $"Stopped process: {selected.Process.DisplayName}"
                : $"Failed to stop process: {selected.Process.DisplayName}";

            if (selectedDashboard)
            {
                _dashboardStarted = _dashboard?.IsRunning is true;
                serviceStatusState = string.Empty;
                UpdateTableCells(defaultStatus);
                UpdateAspireStatusPanel();
            }

            SyncDashboardInventory();
            reloadSelectedProcessLogs = true;
            UpdateProcessPanel();
            UpdateProcessDetailsPanel();
            UpdateProcessLogsPanel(forceReload: true);
            UpdateFooterPanel();
        }

        async Task RestartSelectedProcessAsync()
        {
            var selected = GetSelectedProcessEntry();
            if (selected is null)
            {
                actionStatus = "No process selected.";
                UpdateFooterPanel();
                return;
            }

            var selectedDashboard = selected.Id.Equals(_dashboardProcessId, StringComparison.OrdinalIgnoreCase);
            if (selectedDashboard)
            {
                _dashboardStarted = false;
                ResetTableCells();
                UpdateAspireStatusPanel();
            }

            var restarted = await _processManager.RestartAsync(selected.Id, CancellationToken.None).ConfigureAwait(false);
            actionStatus = restarted
                ? $"Restarted process: {selected.Process.DisplayName}"
                : $"Failed to restart process: {selected.Process.DisplayName}";

            if (selectedDashboard)
            {
                _dashboardStarted = _dashboard?.IsRunning is true;
                serviceStatusState = string.Empty;
                UpdateTableCells(defaultStatus);
                UpdateAspireStatusPanel();
            }

            SyncDashboardInventory();
            reloadSelectedProcessLogs = true;
            UpdateProcessPanel();
            UpdateProcessDetailsPanel();
            UpdateProcessLogsPanel(forceReload: true);
            UpdateFooterPanel();
        }

        async Task DeleteSelectedProcessAsync()
        {
            var selected = GetSelectedProcessEntry();
            if (selected is null)
            {
                actionStatus = "No process selected.";
                UpdateFooterPanel();
                return;
            }

            var removed = await _processManager.RemoveAsync(selected.Id, stopIfRunning: true, CancellationToken.None).ConfigureAwait(false);
            actionStatus = removed
                ? $"Deleted process: {selected.Process.DisplayName}"
                : $"Failed to delete process: {selected.Process.DisplayName}";

            if (selected.Id.Equals(_dashboardProcessId, StringComparison.OrdinalIgnoreCase))
            {
                _dashboardProcessId = null;
                _dashboardStarted = _dashboard?.IsRunning is true;
                serviceStatusState = string.Empty;
                UpdateTableCells(defaultStatus);
                UpdateAspireStatusPanel();
            }

            selectedProcessId = string.Empty;
            processLogsProcessId = string.Empty;
            processLogEntries.Clear();

            SyncDashboardInventory();
            EnsureSelectedProcess();
            reloadSelectedProcessLogs = true;
            UpdateProcessPanel();
            UpdateProcessDetailsPanel();
            UpdateProcessLogsPanel(forceReload: true);
            UpdateFooterPanel();
        }

        string BuildInventoryState()
        {
            return string.Join('|', _processManager
                .List()
                .Select(e => $"{e.Id}:{e.Process.IsRunning}:{e.Process.Pid}:{e.Details}:{string.Join(',', e.ExposedPorts)}"));
        }

        string BuildDashboardDetails()
        {
            if (_dashboard is null)
            {
                return string.Empty;
            }

            var details = new List<string>();
            details.Add(_dashboard.IsRunning ? "running" : "stopped");

            if (_dashboard.Url is { } dashboardUrl)
            {
                details.Add($"url={UrlHelper.ReplaceDefaultRoute(dashboardUrl)}");
            }

            if (otlpEndpoints.Contains("grpc"))
            {
                var grpcReady = _dashboard.OtlpEndpoints?.Any(e => e.Protocol.Contains("grpc", StringComparison.OrdinalIgnoreCase)) is true;
                details.Add(grpcReady ? $"grpc={settings.OtlpPort}" : "grpc=pending");
            }

            if (otlpEndpoints.Contains("http"))
            {
                var httpReady = _dashboard.OtlpEndpoints?.Any(e => e.Protocol.Contains("http", StringComparison.OrdinalIgnoreCase)) is true;
                details.Add(httpReady ? $"http={settings.OtlpHttpPort ?? OtlpOptions.DefaultOtlpHttpPort}" : "http=pending");
            }

            if (dashboardOptions.Mcp.Disabled is false)
            {
                details.Add(_dashboard.McpEndpoint is null ? "mcp=pending" : $"mcp={settings.McpPort}");
            }

            return string.Join(", ", details);
        }

        IReadOnlyList<int> GetDashboardPorts()
        {
            var ports = new HashSet<int>
            {
                settings.DashboardPort
            };

            if (otlpEndpoints.Contains("grpc"))
            {
                ports.Add(settings.OtlpPort);
            }

            if (otlpEndpoints.Contains("http"))
            {
                ports.Add(settings.OtlpHttpPort ?? OtlpOptions.DefaultOtlpHttpPort);
            }

            if (dashboardOptions.Mcp.Disabled is false)
            {
                ports.Add(settings.McpPort);
            }

            return [.. ports
                .Where(p => p is > ushort.MinValue and <= ushort.MaxValue)
                .OrderBy(p => p)];
        }

        string? BuildEnvironmentString(IReadOnlyDictionary<string, string?> environmentVariables)
        {
            if (environmentVariables.Count == 0)
            {
                return null;
            }

            return string.Join(";", environmentVariables.Select(e => $"{e.Key}={e.Value}"));
        }

        void SignalHandler(PosixSignalContext _)
        {
            _.Cancel = true;
            sessionCts.Cancel();
        }

        async Task ShutdownManagedProcessesAsync()
        {
            var dashboardPid = _dashboard?.Pid;

            await _processManager.StopAllAsync(CancellationToken.None);
            await _processManager.RemoveAllAsync(stopIfRunning: false, CancellationToken.None);

            if (dashboardPid is int pid)
            {
                TryTerminateProcessByPid(pid);
            }
        }

        async Task KillAllManagedProcessesAsync()
        {
            var entries = _processManager.List();
            var knownPids = entries
                .SelectMany(entry => new[] { entry.Process.Pid, entry.LastKnownPid })
                .Where(pid => pid is not null)
                .Select(pid => pid!.Value)
                .ToHashSet();

            var knownPorts = entries
                .SelectMany(entry => entry.ExposedPorts)
                .Where(port => port is > ushort.MinValue and <= ushort.MaxValue)
                .ToHashSet();

            foreach (var dashboardPort in GetDashboardPorts())
            {
                knownPorts.Add(dashboardPort);
            }

            if (_dashboard?.Pid is int dashboardPid)
            {
                knownPids.Add(dashboardPid);
            }

            try
            {
                await _processManager.StopAllAsync(CancellationToken.None);
                await _processManager.RemoveAllAsync(stopIfRunning: false, CancellationToken.None);
            }
            catch
            {
                // Continue force-kill path on failures.
            }

            foreach (var pid in knownPids)
            {
                TryTerminateProcessByPid(pid);
            }

            foreach (var ownerPid in GetListeningOwnerPidsByPorts(knownPorts))
            {
                TryTerminateProcessByPid(ownerPid);
            }
        }

        static IReadOnlyCollection<int> GetListeningOwnerPidsByPorts(IReadOnlyCollection<int> ports)
        {
            if (ports.Count == 0 || !RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                return [];
            }

            try
            {
                using var netstat = new Process
                {
                    StartInfo = new ProcessStartInfo
                    {
                        FileName = "netstat",
                        Arguments = "-ano -p tcp",
                        RedirectStandardOutput = true,
                        RedirectStandardError = true,
                        UseShellExecute = false,
                        CreateNoWindow = true
                    }
                };

                if (!netstat.Start())
                {
                    return [];
                }

                var output = netstat.StandardOutput.ReadToEnd();
                netstat.WaitForExit(3000);

                if (netstat.ExitCode != 0 || string.IsNullOrWhiteSpace(output))
                {
                    return [];
                }

                var expectedPorts = ports.ToHashSet();
                var ownerPids = new HashSet<int>();
                var lines = output.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries);

                foreach (var rawLine in lines)
                {
                    var line = rawLine.Trim();
                    if (!line.StartsWith("TCP", StringComparison.OrdinalIgnoreCase))
                    {
                        continue;
                    }

                    var parts = line.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries);
                    if (parts.Length < 5)
                    {
                        continue;
                    }

                    var localEndpoint = parts[1];
                    var state = parts[3];
                    var pidText = parts[4];

                    if (!state.Equals("LISTENING", StringComparison.OrdinalIgnoreCase))
                    {
                        continue;
                    }

                    var separatorIndex = localEndpoint.LastIndexOf(':');
                    if (separatorIndex < 0)
                    {
                        continue;
                    }

                    if (!int.TryParse(localEndpoint[(separatorIndex + 1)..], out var localPort))
                    {
                        continue;
                    }

                    if (!expectedPorts.Contains(localPort))
                    {
                        continue;
                    }

                    if (!int.TryParse(pidText, out var ownerPid))
                    {
                        continue;
                    }

                    if (ownerPid <= 0 || ownerPid == Environment.ProcessId)
                    {
                        continue;
                    }

                    ownerPids.Add(ownerPid);
                }

                return [.. ownerPids];
            }
            catch
            {
                return [];
            }
        }

        static void TryTerminateProcessByPid(int pid)
        {
            try
            {
                var process = Process.GetProcessById(pid);
                process.Kill(entireProcessTree: true);
            }
            catch
            {
                // Ignore failures when process has already exited.
            }
        }
    }

    private (IRenderable Panel, bool LogUpdated) BuildLogPanel()
    {
        const int lineCount = 15;
        var newLogs = Logger.Read("AspireRunner.Core.Dashboard", lineCount);

        _currentLog = _currentLog.Concat(newLogs)
            .TakeLast(lineCount)
            .ToArray();

        if (_currentLog.Length == 0)
        {
            return (new Text(""), false);
        }

        var contentSize = Widgets.IsSmol() ? 10 : 15;
        var visibleLines = Math.Max(AnsiConsole.Profile.Height - contentSize, 1);
        return (
            Panel: new Align(
                new Rows(_currentLog.TakeLast(visibleLines).Select(Widgets.LogRecord)),
                HorizontalAlignment.Left,
                VerticalAlignment.Middle
            ),
            LogUpdated: newLogs.Length > 0
        );
    }

    private static DashboardOptions BuildOptions(Settings args)
    {
        var useHttps = args.UseHttps ?? true;
        var corsConfigured = !string.IsNullOrWhiteSpace(args.CorsAllowedOrigins) || !string.IsNullOrWhiteSpace(args.CorsAllowedHeaders);
        var browserTelemetryEnabled = args.OtlpHttpPort is > ushort.MinValue and <= ushort.MaxValue || corsConfigured;

        var aspireDashboardOptions = new DashboardOptions
        {
            Frontend = new FrontendOptions
            {
                BrowserToken = string.IsNullOrWhiteSpace(args.AuthToken) ? null : args.AuthToken,
                EndpointUrls = UrlHelper.BuildLocalUrl(args.DashboardPort, args.DashboardHttps ?? args.UseHttps ?? true, args.Hostname),
                AuthMode = args.UseAuth || !string.IsNullOrWhiteSpace(args.AuthToken) ? FrontendAuthMode.BrowserToken : FrontendAuthMode.Unsecured
            },
            Otlp = new OtlpOptions
            {
                Cors = browserTelemetryEnabled ? new OtlpCorsOptions() : null,
                PrimaryApiKey = string.IsNullOrWhiteSpace(args.OtlpKey) ? null : args.OtlpKey,
                AuthMode = string.IsNullOrWhiteSpace(args.OtlpKey) ? OtlpAuthMode.Unsecured : OtlpAuthMode.ApiKey
            },
            Mcp = new McpOptions
            {
                Disabled = args.McpPort is 0,
                PrimaryApiKey = string.IsNullOrWhiteSpace(args.McpKey) ? null : args.McpKey,
                AuthMode = string.IsNullOrWhiteSpace(args.McpKey) ? McpAuthMode.Unsecured : McpAuthMode.ApiKey,
                EndpointUrl = args.McpPort is > ushort.MinValue and <= ushort.MaxValue ? UrlHelper.BuildLocalUrl(args.McpPort, args.McpHttps ?? useHttps, args.Hostname) : null
            },
            Runner = new RunnerOptions
            {
                PreferredVersion = args.Version,
                PipeOutput = args.Verbose ?? false,
                LaunchBrowser = args.LaunchBrowser,
                AutoUpdate = args.AutoUpdate ?? true,
                SingleInstanceHandling = args.AllowMultipleInstances ? SingleInstanceHandling.Ignore : SingleInstanceHandling.ReplaceExisting
            }
        };

        if (args.OtlpPort is > ushort.MinValue and <= ushort.MaxValue)
        {
            aspireDashboardOptions.Otlp.EndpointUrl = UrlHelper.BuildLocalUrl(args.OtlpPort, args.OtlpHttps ?? useHttps, args.Hostname);
        }

        if (browserTelemetryEnabled)
        {
            aspireDashboardOptions.Otlp.HttpEndpointUrl = UrlHelper.BuildLocalUrl(args.OtlpHttpPort ?? OtlpOptions.DefaultOtlpHttpPort, args.OtlpHttps ?? useHttps, args.Hostname);
        }

        if (aspireDashboardOptions.Otlp.Cors is not null)
        {
            aspireDashboardOptions.Otlp.Cors.AllowedHeaders = args.CorsAllowedHeaders;
            aspireDashboardOptions.Otlp.Cors.AllowedOrigins = args.CorsAllowedOrigins ?? "*";
        }

        return aspireDashboardOptions;
    }

    private static IReadOnlyCollection<string> GetEnabledEndpoints(DashboardOptions dashboardOptions)
    {
        var enabledEndpoints = new List<string>();
        if (dashboardOptions.Otlp.HttpEndpointUrl is not null)
        {
            enabledEndpoints.Add("http");
        }

        if (dashboardOptions.Otlp.EndpointUrl is not null)
        {
            enabledEndpoints.Add("grpc");
        }

        return enabledEndpoints;
    }

    private static LpcServer? StartLpcServer(IProcessFactory processFactory, Func<Task>? shutdownRequested)
    {
        var server = new LpcServer(
            InMemoryProcessManager.Instance,
            processFactory,
            Logger.DefaultFactory.CreateLogger<LpcServer>(),
            LpcServer.DefaultPort,
            shutdownRequested);

        if (server.Start())
        {
            return server;
        }

        server.Dispose();
        return null;
    }
}