<Project Sdk="Microsoft.NET.Sdk">
    <Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.1.3" />

    <PropertyGroup>
        <TargetFrameworks>net8.0;</TargetFrameworks>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\ProcessManager.Client\ProcessManager.Client.csproj" />
    </ItemGroup>

</Project>
